export const listTypeSongVN = [
  "Tất cả",
  "Nhạc Trẻ",
  "Nhạc Kpop",
  "Nhạc vàng",
  "Nhạc remix",
];
export const listTypeSongEN = [
  "All",
  "NhacTre",
  "NhacKpop",
  "NhacVang",
  "NhacRemix",
];
export const listSongNhacTre = [
  {
    id: 0,
    image: "./image/CenturesImg.jpg",
    artist: "Fall All Boy",
    name: "Centures",
    type: "Nhac Tre",
    album: "album 1",
    time: "3:47",
    play: 81001,
    source: "./mp3/Centuries.mp3",
  },
  {
    id: 1,
    image: "./image/InfinityImg.jpg",
    artist: "Jaymes Young",
    name: "Infinity",
    type: "Nhac Tre",
    album: "album 1",
    time: "5:03",
    play: 81001,
    source: "./mp3/Infinity.mp3",
  },
];
export const listSongNhacKpop = [
  {
    id: 0,
    image: "./image/HeatWavesImg.jpg",
    artist: "Glass Animals",
    name: "Heat Waves",
    type: "Nhac Kpop",
    album: "album 1",
    time: "3:56",
    play: 81001,
    source: "./mp3/HeatWaves.mp3",
  },
  {
    id: 1,
    image: "./image/PartyFavorImg.jpg",
    artist: "Gustixa",
    name: "Party Favor",
    type: "Nhac Kpop",
    album: "album 1",
    time: "4:15",
    play: 81001,
    source: "./mp3/PartyFavor.mp3",
  },
];
export const listSongNhacVang = [
  {
    id: 0,
    image: "./image/HymnImg.jpg",
    artist: "ColdPlay",
    name: "Hymn for the weekend",
    type: "Nhac Vang",
    album: "album 1",
    time: "4:26",
    play: 81001,
    source: "./mp3/Hymn.mp3",
  },
  {
    id: 1,
    image: "./image/RiseImg.jpg",
    artist: "Leaguge Of Legends",
    name: "Rise",
    type: "Nhac Vang",
    album: "album 1",
    time: "3:31",
    play: 81001,
    source: "./mp3/Rise.mp3",
  },
];
export const listSongNhacRemix = [
  {
    id: 0,
    image: "./image/EnemyImg.jpg",
    artist: " Imagine Dragons",
    name: "Enemy",
    type: "Nhac Remix",
    album: "album 1",
    time: "3:34",
    play: 81001,
    source: "./mp3/Enemy.mp3",
  },
  {
    id: 1,
    image: "./image/TryImg.jpg",
    artist: "Pink",
    name: "Try",
    type: "Nhac Remix",
    album: "album 1",
    time: "2:45",
    play: 81001,
    source: "./mp3/Try.mp3",
  },
];
