export const nameOfCatogory = ["Browse Music", "Your Music", "Play List"];
export const listDetailCato = [
  [
    {
      id: 0,
      iconChoose: <i className="fa fa-search" aria-hidden="true"></i>,
      nameChoose: "Discover",
      namePage: "DiscoverPage",
    },
    {
      id: 1,
      iconChoose: <i className="fa fa-headphones" aria-hidden="true"></i>,
      nameChoose: "Songs",
      namePage: "SongPage",
    },
    {
      id: 2,
      iconChoose: <i className="fa fa-book" aria-hidden="true"></i>,
      nameChoose: "Albums",
      namePage: "AlbumsPage",
    },
    {
      id: 3,
      iconChoose: <i className="fa fa-user" aria-hidden="true"></i>,
      nameChoose: "Artist",
      namePage: "ArtistPage",
    },
    {
      id: 4,
      iconChoose: <i className="fa fa-globe" aria-hidden="true"></i>,
      nameChoose: "Music videos",
      namePage: "MusicVideosPage",
    },
    {
      id: 5,
      iconChoose: <i className="fa fa-microphone" aria-hidden="true"></i>,
      nameChoose: "Radio",
      namePage: "RadioPage",
    },
  ],
  [
    {
      id: 6,
      iconChoose: <i className="fa fa-heart" aria-hidden="true"></i>,
      nameChoose: "Favorite",
      namePage: "FavoritePage",
    },
    {
      id: 7,
      iconChoose: <i className="fa fa-history" aria-hidden="true"></i>,
      nameChoose: "History",
      namePage: "HistoryPage",
    },
    {
      id: 8,
      iconChoose: <i className="fa fa-download" aria-hidden="true"></i>,
      nameChoose: "Download Items",
      namePage: "DownloadItemsPage",
    },
    {
      id: 9,
      iconChoose: <i className="fa fa-files-o" aria-hidden="true"></i>,
      nameChoose: "Local Files",
      namePage: "LocalFilesPage",
    },
  ],
  [
    {
      id: 10,
      iconChoose: <i className="fa fa-music" aria-hidden="true"></i>,
      nameChoose: "Pop Music",
      namePage: "PopMusicPage",
    },
    {
      id: 11,
      iconChoose: <i className="fa fa-music" aria-hidden="true"></i>,
      nameChoose: "Dangdut Music",
      namePage: "DangdutMusicPage",
    },
    {
      id: 12,
      iconChoose: <i className="fa fa-music" aria-hidden="true"></i>,
      nameChoose: "Reggea Music",
      namePage: "ReggeaMusicPage",
    },
  ],
];
export const ListMp3 = [
  {
    id: 0,
    image: "./image/CenturesImg.jpg",
    artist: "Fall All Boy",
    name: "Centures",
    time: "3.47",
    source: "./mp3/Centuries.mp3",
  },
  {
    id: 1,
    image: "./image/HeatWavesImg.jpg",
    artist: "Glass Animals",
    name: "Heat Waves",
    time: "3.56",
    source: "./mp3/HeatWaves.mp3",
  },
  {
    id: 2,
    image: "./image/HymnImg.jpg",
    artist: "ColdPlay",
    name: "Hymn for the weekend",
    time: "4.26",
    source: "./mp3/Hymn.mp3",
  },
  {
    id: 3,
    image: "./image/EnemyImg.jpg",
    artist: " Imagine Dragons",
    name: "Enemy",
    time: "3.34",
    source: "./mp3/Enemy.mp3",
  },
  {
    id: 4,
    image: "./image/InfinityImg.jpg",
    artist: "Jaymes Young",
    name: "Infinity",
    time: "5.03",
    source: "./mp3/Infinity.mp3",
  },
  {
    id: 5,
    image: "./image/PartyFavorImg.jpg",
    artist: "Gustixa",
    name: "Party Favor",
    time: "4.15",
    source: "./mp3/PartyFavor.mp3",
  },
  {
    id: 6,
    image: "./image/RiseImg.jpg",
    artist: "Leaguge Of Legends",
    name: "Rise",
    time: "3.31",
    source: "./mp3/Rise.mp3",
  },
  {
    id: 7,
    image: "./image/TryImg.jpg",
    artist: "Pink",
    name: "Try",
    time: "2.45",
    source: "./mp3/Try.mp3",
  },
];
