export const listTopSong = [
  {
    id: 0,
    image: "./image/CenturesImg.jpg",
    artist: "Fall All Boy",
    name: "Centures",
    type: "NhacTre",
    album: "album 1",
    time: "3.47",
    play: 81001,
    source: "./mp3/Centuries.mp3",
  },
  {
    id: 1,
    image: "./image/HeatWavesImg.jpg",
    artist: "Glass Animals",
    name: "Heat Waves",
    type: "NhacKpop",
    album: "album 1",
    time: "3.56",
    play: 81001,
    source: "./mp3/HeatWaves.mp3",
  },
  {
    id: 2,
    image: "./image/HymnImg.jpg",
    artist: "ColdPlay",
    name: "Hymn for the weekend",
    type: "NhacVang",
    album: "album 1",
    time: "4.26",
    play: 81001,
    source: "./mp3/Hymn.mp3",
  },
  {
    id: 3,
    image: "./image/EnemyImg.jpg",
    artist: " Imagine Dragons",
    name: "Enemy",
    type: "NhacRemix",
    album: "album 1",
    time: "3.34",
    play: 81001,
    source: "./mp3/Enemy.mp3",
  },
  {
    id: 4,
    image: "./image/InfinityImg.jpg",
    artist: "Jaymes Young",
    name: "Infinity",
    type: "NhacTre",
    album: "album 1",
    time: "5.03",
    play: 81001,
    source: "./mp3/Infinity.mp3",
  },
  {
    id: 5,
    image: "./image/PartyFavorImg.jpg",
    artist: "Gustixa",
    name: "Party Favor",
    type: "NhacKpop",
    album: "album 1",
    time: "4:15",
    play: 81001,
    source: "./mp3/PartyFavor.mp3",
  },
  {
    id: 6,
    image: "./image/RiseImg.jpg",
    artist: "Leaguge Of Legends",
    name: "Rise",
    type: "NhacVang",
    album: "album 1",
    time: "3:31",
    play: 81001,
    source: "./mp3/Rise.mp3",
  },
  {
    id: 7,
    image: "./image/TryImg.jpg",
    artist: "Pink",
    name: "Try",
    type: "NhacRemix",
    album: "album 1",
    time: "2:45",
    play: 81001,
    source: "./mp3/Try.mp3",
  },
];
